version: '3.3'

services:
  crypto-bot:
    build: .
    container_name: crypto_bot_trading
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
    volumes:
      - ./var:/usr/src/app/var
    restart: unless-stopped
    networks:
      - ppsi_network

networks:
  ppsi_network:
    external: true
